#:schema node_modules/wrangler/config-schema.json
name = "identicat"
main = ".open-next/worker.js"
compatibility_date = "2024-11-18"
compatibility_flags = ["nodejs_compat"]
assets = { directory = ".open-next/assets", binding = "ASSETS" }

[vars]
# GEMINI_API_KEY
